export enum TipoRecurso {
  PARTE = 'PARTE',

  PIEZA = 'PIEZA',

  AGREGADOMAYOR = 'AGREGAD OMAYOR',

  AGREGADOMENOR = 'AGREGAD OMENOR',

  INSUMO = 'INSUMO',

  LUBRICANTE = 'LUBRICANTE',
  COMBUSTIBLE = 'COMBUSTIBLE',
}
